import type { DiffHunk } from "../../types/git";

interface DiffLinesProps {
  hunk: DiffHunk;
  commentedLines: Set<number>;
  selectionStart: number | null;
  selectionEnd: number | null;
  onLineMouseDown: (lineNo: number, event: React.MouseEvent) => void;
  onLineMouseEnter: (lineNo: number) => void;
}

export function HunkHeader({ hunk }: { hunk: DiffHunk }) {
  return (
    <div className="hunk-header">
      @@ -{hunk.old_start},{hunk.old_lines} +{hunk.new_start},{hunk.new_lines}{" "}
      @@
    </div>
  );
}

export function DiffLines({
  hunk,
  commentedLines,
  selectionStart,
  selectionEnd,
  onLineMouseDown,
  onLineMouseEnter,
}: DiffLinesProps) {
  const isLineSelected = (lineNo: number | null) => {
    if (lineNo === null || selectionStart === null) return false;
    const start = Math.min(selectionStart, selectionEnd ?? selectionStart);
    const end = Math.max(selectionStart, selectionEnd ?? selectionStart);
    return lineNo >= start && lineNo <= end;
  };

  return (
    <div className="diff-lines">
      {hunk.lines.map((line, index) => {
        const lineNo = line.new_line_no ?? line.old_line_no;
        const hasComment = lineNo !== null && commentedLines.has(lineNo);
        const isSelected = isLineSelected(lineNo);

        return (
          <div
            key={index}
            className={`diff-line ${line.kind}${hasComment ? " has-comment" : ""}${isSelected ? " selected" : ""}`}
            onMouseDown={(e) => lineNo !== null && onLineMouseDown(lineNo, e)}
            onMouseEnter={() => lineNo !== null && onLineMouseEnter(lineNo)}
          >
            <span className="line-number old">{line.old_line_no ?? ""}</span>
            <span className="line-number new">{line.new_line_no ?? ""}</span>
            <span className="line-marker">
              {line.kind === "addition"
                ? "+"
                : line.kind === "deletion"
                  ? "-"
                  : " "}
            </span>
            {line.highlighted ? (
              // Safe: HTML generated by syntect backend, no user input
              <span
                className="line-content"
                dangerouslySetInnerHTML={{ __html: line.highlighted }}
              />
            ) : (
              <span className="line-content">{line.content}</span>
            )}
            {hasComment && (
              <span className="comment-indicator" title="Has comment" />
            )}
          </div>
        );
      })}
    </div>
  );
}
