// Re-export generated types from ts-rs
// Regenerate with: make generate-types
export type {
  ChangedFile,
  DiffHunk,
  DiffLine,
  FileDiff,
  FileStatus,
  LineKind,
  RepositoryCheckResult,
} from "./generated";

// Import types for use in helper functions
import type { ChangedFile, FileStatus } from "./generated";

// Helper functions (not generated by ts-rs)

/** Helper to get the display status (prefers worktree over index) */
export function getDisplayStatus(file: ChangedFile): FileStatus {
  return file.worktree_status ?? file.index_status ?? "modified";
}

/** Check if file has staged changes */
export function isStaged(file: ChangedFile): boolean {
  return file.index_status !== null;
}

/** Check if file has unstaged changes */
export function isUnstaged(file: ChangedFile): boolean {
  return file.worktree_status !== null;
}
